export const bannerSources = [
  {
    slug: 'home-hero-samsung-galaxy-s26-series',
    title: 'Samsung Galaxy S26 Series',
    position: 'home-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773117620989-1968x790-main-banner-S26-1.jpg',
    link: '/danh-muc/dien-thoai',
    order: 0,
    sourceUrl: 'src/data/siteData.js:219',
  },
  {
    slug: 'home-hero-galaxy-tab',
    title: 'Galaxy Tab',
    position: 'home-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773028447455-top-colection-galaxy-tab.jpg',
    link: '/danh-muc/tablet',
    order: 1,
    sourceUrl: 'src/data/siteData.js:219',
  },
  {
    slug: 'home-hero-samsung-galaxy-s25',
    title: 'Samsung Galaxy S25',
    position: 'home-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773215461393-984x395_Main-Banner-samsung-s25-1.jpg',
    link: '/danh-muc/dien-thoai',
    order: 2,
    sourceUrl: 'src/data/siteData.js:219',
  },
  {
    slug: 'home-featured-galaxy-a-series',
    title: 'Galaxy A Series',
    position: 'home-featured-category',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1772705147684-390x490-Galaxy-A-Top-Collection-Banner-2-1.jpg',
    link: '/danh-muc/dien-thoai',
    order: 0,
    sourceUrl: 'src/data/siteData.js:184',
  },
  {
    slug: 'home-featured-tablet-android',
    title: 'Tablet Android',
    position: 'home-featured-category',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773028447455-top-colection-galaxy-tab.jpg',
    link: '/danh-muc/tablet',
    order: 1,
    sourceUrl: 'src/data/siteData.js:184',
  },
  {
    slug: 'home-featured-thu-cu-doi-moi',
    title: 'Thu Cũ Đổi Mới',
    position: 'home-featured-category',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1765439122070-390x490_Top-Collection-Banner_thu-cu-doi-moi-new.jpg',
    link: '/danh-muc/thu-cu-doi-moi',
    order: 2,
    sourceUrl: 'src/data/siteData.js:184',
  },
  {
    slug: 'home-featured-phu-kien-cong-nghe',
    title: 'Phụ kiện công nghệ',
    position: 'home-featured-category',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773028447455-top-colection-galaxy-tab.jpg',
    link: '/danh-muc/phu-kien',
    order: 3,
    sourceUrl: 'src/data/siteData.js:184',
  },
  {
    slug: 'home-mid-banner-bao-hanh',
    title: 'Banner bảo hành',
    position: 'home-mid',
    image: 'https://bizweb.dktcdn.net/100/112/815/themes/966034/assets/banner.jpg?1768028836881',
    link: '/tin-tuc',
    order: 0,
    sourceUrl: 'src/data/siteData.js:211',
  },
  {
    slug: 'home-tablet-promo-left',
    title: 'Tablet promo trái',
    position: 'home-tablet-promo',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1770690260094-Android-Adapt-xiaomi-reedmi-pad-2-pro-1.jpg',
    link: '/danh-muc/tablet',
    order: 0,
    sourceUrl: 'src/app/(website)/page.js:160',
  },
  {
    slug: 'home-tablet-promo-right',
    title: 'Tablet promo phải',
    position: 'home-tablet-promo',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773028447455-top-colection-galaxy-tab.jpg',
    link: '/danh-muc/tablet',
    order: 1,
    sourceUrl: 'src/app/(website)/page.js:160',
  },
  {
    slug: 'home-sky-left',
    title: 'Sky banner trái',
    position: 'home-sky',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1772422775466-roll1-2.jpg',
    order: 0,
    sourceUrl: 'src/app/(website)/page.js:33',
  },
  {
    slug: 'home-sky-right',
    title: 'Sky banner phải',
    position: 'home-sky',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773022062519-s26-pre-roll-1.jpg',
    order: 1,
    sourceUrl: 'src/app/(website)/page.js:44',
  },
  {
    slug: 'promo-tuan-le-vang',
    title: 'Tuần lễ vàng',
    position: 'promo-campaign',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773108102511-hot-section-banner-desktop-tuan-le-vang.jpg',
    mobileImage: 'https://cdn.dienthoaigiakho.vn/photos/1773107163592-hot-section-banner-mobile-tuan-le-vang.jpg',
    link: '/wow/mua-online-gia-re',
    order: 0,
    sourceUrl: 'pages-json/wow__mua-online-gia-re.json:17',
  },
  {
    slug: 'collection-hero-dien-thoai',
    title: 'Điện thoại',
    position: 'collection-hero',
    image: 'https://bizweb.dktcdn.net/100/112/815/themes/966034/assets/banner.jpg?1768028836881',
    link: '/danh-muc/dien-thoai',
    order: 0,
    sourceUrl: 'src/data/siteData.js:288',
  },
  {
    slug: 'collection-hero-phu-kien',
    title: 'Phụ kiện',
    position: 'collection-hero',
    image: 'https://bizweb.dktcdn.net/100/112/815/themes/966034/assets/banner2.jpg?1768028836881',
    link: '/danh-muc/phu-kien',
    order: 1,
    sourceUrl: 'src/data/siteData.js:307',
  },
  {
    slug: 'collection-hero-tablet',
    title: 'Tablet',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773028447455-top-colection-galaxy-tab.jpg',
    link: '/danh-muc/tablet',
    order: 2,
    sourceUrl: 'src/data/siteData.js:325',
  },
  {
    slug: 'collection-hero-linh-kien',
    title: 'Linh kiện',
    position: 'collection-hero',
    image: 'https://bizweb.dktcdn.net/100/112/815/products/pin-15-promax.png?v=1764920853963',
    link: '/danh-muc/linh-kien',
    order: 3,
    sourceUrl: 'src/data/siteData.js:343',
  },
  {
    slug: 'collection-hero-hang-cu',
    title: 'Máy Cũ Giá Rẻ',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1772792984416-top-colection-may-cu-1.jpg',
    link: '/danh-muc/hang-cu',
    order: 4,
    sourceUrl: 'src/data/siteData.js:361',
  },
  {
    slug: 'collection-hero-thu-cu-doi-moi',
    title: 'Thu Cũ Đổi Mới',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1765439122070-390x490_Top-Collection-Banner_thu-cu-doi-moi-new.jpg',
    link: '/danh-muc/thu-cu-doi-moi',
    order: 5,
    sourceUrl: 'src/data/siteData.js:379',
  },
  {
    slug: 'collection-hero-am-thanh',
    title: 'Âm Thanh',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1663990385429-airpods-pro-2-thumbnail.jpg',
    link: '/danh-muc/am-thanh',
    order: 6,
    sourceUrl: 'src/data/siteData.js:397',
  },
  {
    slug: 'collection-hero-smartwatch',
    title: 'Đồng Hồ',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1715769095134-icon-watch.png',
    link: '/danh-muc/smartwatch',
    order: 7,
    sourceUrl: 'src/data/siteData.js:415',
  },
  {
    slug: 'collection-hero-khuyen-mai',
    title: 'Khuyến Mãi',
    position: 'collection-hero',
    image: 'https://cdn.dienthoaigiakho.vn/photos/1773105631169-roll-banner-tuan-le-vangjpg.jpg',
    link: '/danh-muc/khuyen-mai',
    order: 8,
    sourceUrl: 'src/data/siteData.js:433',
  },
];
