/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    categories: Category;
    products: Product;
    banners: Banner;
    orders: Order;
    carts: Cart;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    promotions: Promotion;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  fullName: string;
  phone: string;
  address?: string | null;
  city?: string | null;
  district?: string | null;
  ward?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  /**
   * Dùng khi ảnh được sync từ CDN/external source.
   */
  externalURL?: string | null;
  mime?: string | null;
  cloudinary?: {
    publicId?: string | null;
    secureUrl?: string | null;
    resourceType?: string | null;
    format?: string | null;
    bytes?: number | null;
    version?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug: string;
  parent?: (string | null) | Category;
  icon?: (string | null) | Media;
  description?: string | null;
  heroBanner?: (string | null) | Banner;
  banners?: (string | Banner)[] | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: string;
  title: string;
  key: string;
  slug?: string | null;
  image: string | Media;
  mobileImage?: (string | null) | Media;
  link?: string | null;
  ctaHref?: string | null;
  position:
    | 'home-hero'
    | 'home-featured-category'
    | 'home-mid'
    | 'home-tablet-promo'
    | 'home-sky'
    | 'collection-hero'
    | 'promo-campaign'
    | 'home-grid'
    | 'category-hero'
    | 'promotion'
    | 'page-block';
  active?: boolean | null;
  startAt?: string | null;
  endAt?: string | null;
  sortOrder?: number | null;
  order?: number | null;
  sourceUrl?: string | null;
  products?: (string | Product)[] | null;
  categories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  /**
   * Khóa gom bản ghi trùng khi import; ưu tiên hơn slug nếu có.
   */
  productGroup?: string | null;
  productIdentity?: string | null;
  sku?: string | null;
  status: 'draft' | 'active' | 'out-of-stock' | 'archived';
  price: number;
  originalPrice?: number | null;
  inventory?:
    | {
        label: string;
        quantity: number;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Được giữ để tương thích flow giỏ hàng/đơn hàng hiện tại.
   */
  stock?: number | null;
  isActive?: boolean | null;
  featured?: boolean | null;
  category?: (string | null) | Category;
  categorySlug: string;
  brand?: string | null;
  family?: string | null;
  image: string | Media;
  mainImage?: (string | null) | Media;
  gallery?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  technical_specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  variants?:
    | {
        name: string;
        sku?: string | null;
        price?: number | null;
        stock?: number | null;
        color?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  labels?:
    | {
        text: string;
        tone?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  banners?: (string | Banner)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  source?: {
    provider?: string | null;
    sourceId?: string | null;
    url?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderCode: string;
  customer?: (string | null) | Customer;
  items: {
    productSlug: string;
    productName: string;
    variant?: string | null;
    price: number;
    quantity: number;
    image?: string | null;
    id?: string | null;
  }[];
  total: number;
  shippingAddress?: {
    fullName?: string | null;
    phone?: string | null;
    address?: string | null;
    city?: string | null;
    district?: string | null;
    ward?: string | null;
  };
  paymentMethod?: ('cod' | 'bank' | 'installment') | null;
  status?: ('pending' | 'confirmed' | 'shipping' | 'delivered' | 'cancelled') | null;
  note?: string | null;
  adminNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Giỏ hàng server-side
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  customer: string | Customer;
  items?:
    | {
        productSlug: string;
        productName?: string | null;
        variant?: string | null;
        price?: number | null;
        quantity: number;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (string | null) | Media;
  featuredImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('tin-tuc' | 'review' | 'khuyen-mai' | 'huong-dan') | null;
  author?: (string | null) | User;
  publishedAt?: string | null;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * Duong dan public khong co dau / o dau. Ho tro nested route, vi du: info/chinh-sach-bao-mat
   */
  routePath: string;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
    banner?: (string | null) | Banner;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  blocks?:
    | {
        blockType: 'rich-text' | 'banner' | 'product-list' | 'media';
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (string | null) | Media;
        banner?: (string | null) | Banner;
        products?: (string | Product)[] | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'banners';
        value: string | Banner;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  address?: T;
  city?: T;
  district?: T;
  ward?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  externalURL?: T;
  mime?: T;
  cloudinary?:
    | T
    | {
        publicId?: T;
        secureUrl?: T;
        resourceType?: T;
        format?: T;
        bytes?: T;
        version?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  icon?: T;
  description?: T;
  heroBanner?: T;
  banners?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  productGroup?: T;
  productIdentity?: T;
  sku?: T;
  status?: T;
  price?: T;
  originalPrice?: T;
  inventory?:
    | T
    | {
        label?: T;
        quantity?: T;
        available?: T;
        id?: T;
      };
  stock?: T;
  isActive?: T;
  featured?: T;
  category?: T;
  categorySlug?: T;
  brand?: T;
  family?: T;
  image?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  description?: T;
  highlights?:
    | T
    | {
        value?: T;
        id?: T;
      };
  specs?: T;
  technical_specifications?: T;
  specifications?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        price?: T;
        stock?: T;
        color?: T;
        image?: T;
        id?: T;
      };
  labels?:
    | T
    | {
        text?: T;
        tone?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  banners?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  source?:
    | T
    | {
        provider?: T;
        sourceId?: T;
        url?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  slug?: T;
  image?: T;
  mobileImage?: T;
  link?: T;
  ctaHref?: T;
  position?: T;
  active?: T;
  startAt?: T;
  endAt?: T;
  sortOrder?: T;
  order?: T;
  sourceUrl?: T;
  products?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderCode?: T;
  customer?: T;
  items?:
    | T
    | {
        productSlug?: T;
        productName?: T;
        variant?: T;
        price?: T;
        quantity?: T;
        image?: T;
        id?: T;
      };
  total?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        address?: T;
        city?: T;
        district?: T;
        ward?: T;
      };
  paymentMethod?: T;
  status?: T;
  note?: T;
  adminNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  customer?: T;
  items?:
    | T
    | {
        productSlug?: T;
        productName?: T;
        variant?: T;
        price?: T;
        quantity?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  publishedDate?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  routePath?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        banner?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  blocks?:
    | T
    | {
        blockType?: T;
        title?: T;
        content?: T;
        image?: T;
        banner?: T;
        products?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  contact?: {
    phone?: string | null;
    hotline?: string | null;
    email?: string | null;
    address?: string | null;
    workingHours?: string | null;
  };
  social?: {
    facebook?: string | null;
    zalo?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  header?: {
    topBarText?: string | null;
  };
  footer?: {
    address?: string | null;
    hotline?: string | null;
    email?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  payment?: {
    bankName?: string | null;
    bankAccountNumber?: string | null;
    bankAccountName?: string | null;
    bankQRImage?: (string | null) | Media;
  };
  integrations?: {
    freeShipThreshold?: number | null;
    telegramBotToken?: string | null;
    telegramChatId?: string | null;
  };
  phone?: string | null;
  hotline?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  facebookUrl?: string | null;
  zaloUrl?: string | null;
  youtubeUrl?: string | null;
  tiktokUrl?: string | null;
  topBarText?: string | null;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  bankQRImage?: (string | null) | Media;
  freeShipThreshold?: number | null;
  telegramBotToken?: string | null;
  telegramChatId?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  active?: boolean | null;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  banner?: (string | null) | Media;
  linkedProducts?: (string | Product)[] | null;
  linkedBanners?: (string | Banner)[] | null;
  startAt?: string | null;
  endAt?: string | null;
  couponCodes?:
    | {
        code: string;
        discount: number;
        minOrder?: number | null;
        expiryDate?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  activePromotion?: boolean | null;
  promotionTitle?: string | null;
  promotionBanner?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        phone?: T;
        hotline?: T;
        email?: T;
        address?: T;
        workingHours?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        zalo?: T;
        youtube?: T;
        tiktok?: T;
      };
  header?:
    | T
    | {
        topBarText?: T;
      };
  footer?:
    | T
    | {
        address?: T;
        hotline?: T;
        email?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  payment?:
    | T
    | {
        bankName?: T;
        bankAccountNumber?: T;
        bankAccountName?: T;
        bankQRImage?: T;
      };
  integrations?:
    | T
    | {
        freeShipThreshold?: T;
        telegramBotToken?: T;
        telegramChatId?: T;
      };
  phone?: T;
  hotline?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  facebookUrl?: T;
  zaloUrl?: T;
  youtubeUrl?: T;
  tiktokUrl?: T;
  topBarText?: T;
  bankName?: T;
  bankAccountNumber?: T;
  bankAccountName?: T;
  bankQRImage?: T;
  freeShipThreshold?: T;
  telegramBotToken?: T;
  telegramChatId?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  content?: T;
  banner?: T;
  linkedProducts?: T;
  linkedBanners?: T;
  startAt?: T;
  endAt?: T;
  couponCodes?:
    | T
    | {
        code?: T;
        discount?: T;
        minOrder?: T;
        expiryDate?: T;
        isActive?: T;
        id?: T;
      };
  activePromotion?: T;
  promotionTitle?: T;
  promotionBanner?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}